# Generated by Django 6.0.3 on 2026-03-18 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='https://gitlab.ums.ac.id')),
                ('private_token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi GitLab',
            },
        ),
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Mingguan'), ('monthly', 'Bulanan')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_commits', models.IntegerField(default=0)),
                ('total_push_events', models.IntegerField(default=0)),
                ('total_merge_requests', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_additions', models.IntegerField(default=0)),
                ('total_deletions', models.IntegerField(default=0)),
                ('active_projects', models.JSONField(default=list)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('staf', 'period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='GitLabActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('push', 'Push'), ('merge_request', 'Merge Request'), ('issue', 'Issue'), ('comment', 'Comment'), ('pipeline', 'Pipeline')], max_length=20)),
                ('project_name', models.CharField(max_length=200)),
                ('project_id', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('commits_count', models.IntegerField(default=0)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('activity_date', models.DateTimeField()),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aktivitas GitLab',
                'verbose_name_plural': 'Aktivitas GitLab',
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['staf', 'activity_date'], name='gitlab_anal_staf_id_b63a88_idx'), models.Index(fields=['activity_type'], name='gitlab_anal_activit_888e09_idx')],
            },
        ),
    ]
