# Generated by Django 6.0.3 on 2026-03-18 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=300)),
                ('name_with_namespace', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('web_url', models.URLField()),
                ('namespace', models.CharField(blank=True, max_length=200)),
                ('visibility', models.CharField(default='private', max_length=20)),
                ('default_branch', models.CharField(blank=True, max_length=100)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('star_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyek GitLab',
                'verbose_name_plural': 'Proyek GitLab',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_username', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=200)),
                ('author_email', models.CharField(blank=True, max_length=200)),
                ('commit_hash', models.CharField(max_length=40)),
                ('message', models.TextField(blank=True)),
                ('committed_at', models.DateTimeField()),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='gitlab_analysis.gitlabproject')),
                ('staf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_commits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-committed_at'],
                'indexes': [models.Index(fields=['project', 'committed_at'], name='gitlab_anal_project_6d90bb_idx'), models.Index(fields=['gitlab_username'], name='gitlab_anal_gitlab__b31f45_idx')],
                'unique_together': {('project', 'commit_hash')},
            },
        ),
    ]
