# Generated by Django 6.0.3 on 2026-03-18 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_analysis', '0002_gitlabproject_projectcommit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.IntegerField()),
                ('issue_iid', models.IntegerField()),
                ('issue_title', models.CharField(max_length=500)),
                ('issue_url', models.URLField(blank=True)),
                ('issue_state', models.CharField(default='opened', max_length=20)),
                ('note_id', models.IntegerField()),
                ('author_username', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_comments', to='gitlab_analysis.gitlabproject')),
                ('staf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komentar Issue',
                'verbose_name_plural': 'Komentar Issue',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'issue_iid'], name='gitlab_anal_project_170048_idx'), models.Index(fields=['author_username', 'created_at'], name='gitlab_anal_author__63a075_idx'), models.Index(fields=['created_at'], name='gitlab_anal_created_250176_idx')],
                'unique_together': {('project', 'note_id')},
            },
        ),
    ]
