# Generated by Django 6.0.3 on 2026-03-18 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_analysis', '0003_issuecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuecomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Komentar', 'verbose_name_plural': 'Komentar'},
        ),
        migrations.RemoveIndex(
            model_name='issuecomment',
            name='gitlab_anal_project_170048_idx',
        ),
        migrations.AlterUniqueTogether(
            name='issuecomment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='comment_type',
            field=models.CharField(choices=[('issue', 'Issue'), ('commit', 'Commit')], default='issue', max_length=10),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='commit_message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='commit_sha',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='commit_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='line_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='issue_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='issue_iid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='issue_state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='issue_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='note_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='issuecomment',
            unique_together={('project', 'note_id', 'comment_type')},
        ),
        migrations.AddIndex(
            model_name='issuecomment',
            index=models.Index(fields=['project', 'comment_type'], name='gitlab_anal_project_88436d_idx'),
        ),
    ]
